### ISSUE TITLE
Add parameter continue-on-error

### ISSUE THREAD

**Issue by kvrhdn** [honeycombio/gha-buildevents#10]
I've seen gha-buildevents failing occasionally if GitHub releases is down (the download of `buildevents` fails). While this is fairly rare, as a user I'd prefer to run my build without instrumentation instead.

TODO:
- add a parameter to enable/disable `fail-on-error` or `fail-silenty`
- maybe change the default to not fail on error?

**Comment by dstrelau** [comment]
Thank you for submitting this issue! In an effort to better respond to new issues, we're closing old, inactive issues like this one. If you feel this issue is still important to consider, please feel free to reopen it.
