### ISSUE TITLE
Be able to deal with slashes '/' in dataset names

### ISSUE THREAD

**Issue by kvrhdn** [honeycombio/gha-buildevents#11]
From go-honeycombio I've discovered that slashes (`/`) are replaced by dashes (`-`) in URLs. You can observe this in the UI.

Code to deal with this: https://github.com/kvrhdn/go-honeycombio/blob/main/client.go#L183

`gha-buildevents` also accepts a dataset name, if this names contains a slash we should replace it with a dash.

**Comment by kvrhdn** [comment]
This is related to issue https://github.com/honeycombio/buildevents/issues/72 and PR https://github.com/honeycombio/buildevents/pull/73. I'd definitely prefer this to be handled in buildevents itself.

**Comment by dstrelau** [comment]
Thank you for submitting this issue! In an effort to better respond to new issues, we're closing old, inactive issues like this one. If you feel this issue is still important to consider, please feel free to reopen it.
