### ISSUE TITLE
Allow calling this action without generating an event

### ISSUE THREAD

**Issue by tay-bird** [honeycombio/gha-buildevents#148]
**Is your feature request related to a problem? Please describe.**

The new major version that allows tracing an entire workflow has a small nuisance: When the `honeycombio/gha-buildevents@v2` action is included in a job, it always generates an OTEL event that represents only the setup step.

In our workflows, we want to generate one event per job. The additional event generated at the start of each job clutters up our trace view.

**Describe the solution you'd like**

Here are two possible approaches that could be implemented in this project:

<details><summary>Approach A: Allow disabling the default event</summary>
Add a new parameter called `send-event` with the default value `true`.

When set to `false`, the action would not send an event during set up. The functionality of the action would be limited to installing `buildevents` and setting necessary environment variables (`BUILDEVENT_DATASET`, `BUILDEVENT_APIKEY`, etc.).

In this approach, the user must call `buildevents` to create events as desired.
</details>

<details><summary>Approach B: Allow generating a job-level event</summary>
Add a new parameter called `job-event` with the default value `false`.

When set to `true`, the action would send an event to represent the entire job, not just the setup step.

In this approach, the user is not required to call `buildevents` to create a job-level event.
</details>

**Describe alternatives you've considered**

Instead of using the `honeycombio/gha-buildevents@v2` action at the start of every job, we only use it at the beginning and end of the workflow. In order to generate one job per step, we configured environment variables at the workflow level and created our own reusable action.

At the workflow level, we set env vars like this:
```
env:
  BUILDEVENT_DATASET: gha-ci
  BUILDEVENT_APIKEY: ${{ secrets.BUILDEVENTS_APIKEY }}
```

At the beginning of each job, we install `buildevents` and configure it like this:
```
run: |
  # If this is a matrix job, set STEP_NAME_SEPARATOR to '_'. Otherwise,
  # set it to an empty string.
  #
  STEP_NAME_SEPARATOR=${{ (contains(join(matrix.*, '_'), '_') && '_') || '' }}

  # If this is a matrix job, concatenate matrix values with a '_'
  # separator and set STEP_NAME_MATRIX to that value. Otherwise, set it to
  # an empty string.
  #
  STEP_NAME_MATRIX=${{ (contains(join(matrix.*, '_'), '_') && join(matrix.*, '_')) || '' }}

  # Set the STEP_ID to the job name. If this is a matrix job, append the
  # matrix values.
  #
  echo "STEP_ID=${GITHUB_JOB}${STEP_NAME_SEPARATOR}${STEP_NAME_MATRIX}" >> $GITHUB_ENV

  # Record the start time of this job.
  #
  echo "STEP_START=$(date +%s)" >> $GITHUB_ENV

  # Download the `buildevents` tool.
  #
  curl -L -o $RUNNER_TOOL_CACHE/buildevents https://github.com/honeycombio/buildevents/releases/latest/download/buildevents-linux-amd64

  # Make `buildevents` executable.
  #
  chmod 755 $RUNNER_TOOL_CACHE/buildevents
```

At the end of each job, we use `always()` to send the event like this:
```
run: $RUNNER_TOOL_CACHE/buildevents step ${{ inputs.trace-id }} $STEP_ID $STEP_START $STEP_ID
```

**Additional context**

Screenshots:

<details><summary>This is the undesired state.</summary>

  <img width="1417" alt="Screen Shot 2022-09-20 at 12 12 38 PM" src="https://user-images.githubusercontent.com/2468680/191344394-1f25a865-2bc1-4bde-9ec9-1ab784074c0b.png">

</details>

<details><summary>This is the desired state.</summary>

<img width="1413" alt="Screen Shot 2022-09-20 at 12 34 04 PM" src="https://user-images.githubusercontent.com/2468680/191348389-e988c805-26c5-419f-9a1f-ead0be6c3895.png">

</details>

**Comment by tay-bird** [comment]
p.s. happy to take a crack at PRing this if the idea sounds workable and a maintainer can point me at a preferred solution. :)

**Comment by jharley** [comment]
Thanks for your patience!

We're into `Approach A` with the name of the parameter slightly altered to `send-init-event`.

If you're still interested in contributing that work we'd gladly accept/support that effort!
