### ISSUE TITLE
[Request]: gracefully stub out non-supported platforms, provide customizable points for custom binary

### ISSUE THREAD

**Issue by kwonoj** [honeycombio/gha-buildevents#165]
**Is your feature request related to a problem? Please describe.**

Currently, installing `gha-buildevents` fails straightly if a platform is not supported, such as Windows. This makes job execution definition tricky with matrix configuration for the different platforms. For example, if someone have a pseudo-job like below:

```
- matrix:
    os: 
      windows-latest
      ubuntu-latest

- name: install gha-events
  if: ${{ matrix.os }} != "windows-latest"
  ...

- name: run actual command
  run: |
   buildevents cmd ... 
```

now `buildevents` will fail on windows since gha-events is not installed. This is expected outcome, and the way workaround is each run step to check if given matrix have buildevents (or supported os) then invoke buildevents or actual command selectively - while this makes workflow definition cumbersome as each run step needs nearly duplicated one with `if` condition.

**Describe the solution you'd like**

I hope if there are few built in supports like

- `gha-buildevents` can be installed on any platform
- when on not supported platform, `buildevents` stubs out then invoke commmand directly, with some warning messages
-  some configurable point to specify custom binaries for non-supported platform, if someone have in house implementation for the limited usecase.

**Describe alternatives you've considered**

I may wrong and some of these are already supported so this may not be needed at all.

**Additional context**

**Comment by jharley** [comment]
With #286 bringing in Windows support, I'm going to close this out for  now. If this is still something you're looking for @kwonoj please reopen the issue or open a new issue describing what you'd like to see.
