### ISSUE TITLE
Make buildevents download configurable

### ISSUE THREAD

**Issue by shlevy** [honeycombio/gha-buildevents#57]
It would be great to be able to pin a specific version, or even provide our own.

**Comment by kvrhdn** [comment]
What do you mean with _pin a specific version, or even provide our own_? I'd assume that if you pin the version, this would be a version the user provides.

IMO it makes sense to default to `latest`, this way you'll always get bug fixes and I'm not very worried about instabilities being added by Honeycomb.io.

### If anyone wants to pick this up:

The download url is currently hardcoded to latest: https://github.com/kvrhdn/gha-buildevents/blob/f9bfe4eb0a4be2a660c40491bd4e6861413e87ca/src/buildevents.ts#L13-L16

We should be able to introduce a new input to specify the version and if a version is specified we can use this url instead:
```js
"https://github.com/honeycombio/buildevents/releases/download/${buildeventsVersion}/buildevents-linux-amd64"
```

A possible solution would be:
- a new input should be added to `action.yaml`: https://github.com/kvrhdn/gha-buildevents/blob/main/action.yaml#L9
- you can grab them using `core.getInput('<input name>')`, for instance: https://github.com/kvrhdn/gha-buildevents/blob/f9bfe4eb0a4be2a660c40491bd4e6861413e87ca/src/index.ts#L19
- we can extend `install` to accept a parameter `version` https://github.com/kvrhdn/gha-buildevents/blob/f9bfe4eb0a4be2a660c40491bd4e6861413e87ca/src/buildevents.ts#L10
- and then we just have to use a different URL depending on the value of version 🙂

**Comment by shlevy** [comment]
By provide our own I mean something like https://github.com/scarf-sh/gha-buildevents/commit/93a8dc3ef39a19cc0834027c025bd88db283f0e5 where we use a version with https://github.com/honeycombio/buildevents/pull/99 added

**Comment by dstrelau** [comment]
Thank you for submitting this issue! In an effort to better respond to new issues, we're closing old, inactive issues like this one. If you feel this issue is still important to consider, please feel free to reopen it.
